/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;
import java.io.BufferedReader;
import org.json.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.*;
import java.util.Scanner;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ABHIJITH H
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        textarea.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keytf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        notf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextPane();
        label1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(823, 300));
        jPanel1.setLayout(null);
        jPanel1.add(keytf);
        keytf.setBounds(610, 30, 200, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Scrape");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 80, 90, 30);
        jPanel1.add(notf);
        notf.setBounds(610, 80, 100, 30);

        jScrollPane1.setViewportView(textarea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 220, 510, 60);

        label1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        label1.setText("Click 'Scrape' to download images. This may take a few seconds.");
        jPanel1.add(label1);
        label1.setBounds(290, 160, 510, 16);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("ROG Fonts", 0, 30)); // NOI18N
        jLabel3.setText("SCRAPER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 140, 220, 30);

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 0, 30)); // NOI18N
        jLabel4.setText("UNSPLASH");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 100, 220, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Scrape images from unsplash.com");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 210, 250, 26);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 290, 300);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("Enter Keyword (cars,nature,wallpaper,etc) :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 40, 310, 18);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Number of images:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 90, 140, 18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void download(String src,File filename){
    try{
        URL url=new URL(src);
        URLConnection con=url.openConnection();
        con.connect();
        InputStream in=con.getInputStream();
        
        
        FileOutputStream out=new FileOutputStream(filename);
        
        
        byte buffer[]=new byte[4096];
        int bytesReaded;
        
        while((bytesReaded=in.read(buffer))!= -1){
            out.write(buffer,0,bytesReaded);
        
        }
        out.close();
        in.close();
        StyledDocument doc = textarea.getStyledDocument();
   doc.insertString(doc.getLength(), "Downloaded: " + filename + "\n", null);
        System.out.println("Downloaded: " + filename);
//        int n=0;
//        n++;
//        textarea.setText("Downloaded: " + filename);
  


        
        
        
    
    
    }catch(Exception e){System.out.println(e);}
        
        


}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       label1.setText("Please wait scrapping images....");
       String keyword=keytf.getText();
       int num=Integer.parseInt(notf.getText());
       int page=1;
       int n=0;
       int numcheck=num;
       int flag1=0;
       String userHome = System.getProperty("user.home");
        String downloadPath = userHome + "/Downloads/Scrapper";
        File dir = new File(downloadPath);
        if (!dir.exists()) dir.mkdirs();

       while(num!=0){
       try{
            String url=String.format("https://unsplash.com/napi/search/photos?page=%d&per_page=20&query=%s",page,keyword);
           URL downloadurl=new URL(url);
           HttpURLConnection con=(HttpURLConnection) downloadurl.openConnection();
           con.setRequestMethod("GET");
           con.connect();
           int code=con.getResponseCode();
           if(con.getResponseCode()!=200){
           
               throw new RuntimeException("HttpResponseCode: " + code);
           
           }else{
                BufferedReader buff=new BufferedReader(new InputStreamReader(con.getInputStream()));
                String input;
                StringBuilder response=new StringBuilder();
                while((input=buff.readLine())!= null){
                    response.append(input);
                }
                buff.close();
                
//                System.out.println(response);
                JSONObject jobj=new JSONObject(response.toString());
                System.out.println("------------------");
                JSONArray results=jobj.getJSONArray("results");
              
                for(int i=0;i<19;i++){
                    JSONObject id=results.getJSONObject(i);
                    String fullurl=id.getJSONObject("urls").getString("full");
                     String filename=keyword+"_"+page+"_"+i+"."+"jpeg";
                     File outputFile = new File(dir, filename);
                    download(fullurl,outputFile);
                    n++;
                    flag1++;
                   
                    num--;
                    
                    if((n<5 && n==numcheck) || (flag1==numcheck)){
                        break;
                    }else if(n==5 ){
                        n=0;
                        page++;
                        
                        break;
                        
                    }
                    
                
                }
                
                
           }
       
       
       
       
       
       }catch(Exception e){System.out.println(e); break;}}
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keytf;
    private javax.swing.JLabel label1;
    private javax.swing.JTextField notf;
    private javax.swing.JTextPane textarea;
    // End of variables declaration//GEN-END:variables
}
